### ISSUE TITLE
Request timed  out when adding a document to the watson collection

### ISSUE THREAD

**Issue by Nabarun** [watson-developer-cloud/salesforce-sdk#101]
I am trying to upload a sample document from Salesforce Apex class to IBM Watson. I am trying with the following snippet but am getting this error

{
  "code" : 500,
  "error" : "Request timed out, please try again."
}

Somehow it is getting timed out.

```apex         
            Blob fileBlob = Blob.valueOf('This is a sample pdf file');
            IBMDiscoveryV1 discovery = new IBMDiscoveryV1('2017-11-07');
            discovery.setEndPoint('https://gateway.watsonplatform.net/discovery/api');
            discovery.setUsernameAndPassword('<<userId>>', '<<password>>');
            IBMDiscoveryV1Models.AddDocumentOptionsBuilder builder = new IBMDiscoveryV1Models.AddDocumentOptionsBuilder(
                    '<<environmentId>>,
                    '<<collectionId>>');

            IBMWatsonFile.FileBuilder fileBuilder = new IBMWatsonFile.FileBuilder();
            fileBuilder.name('Sample.pdf');
            fileBuilder.body(fileBlob);
            IBMWatsonFile file = fileBuilder.build();

            builder.file(file);
            IBMDiscoveryV1Models.AddDocumentOptions options = builder.build();

            docResponse = discovery.addDocument(options);
            System.debug(docResponse.getDocumentId());
```

**Comment by germanattanasio** [comment]
How big is your document? Right now the timeout is 120 seconds. See https://github.com/watson-developer-cloud/salesforce-sdk/blob/master/force-app/main/default/classes/IBMWatsonClient.cls#L2

**Comment by lpatino10** [comment]
Hey @Nabarun. Thanks for submitting this issue.

I'm seeing similar errors when trying it myself, so I'm going to be looking into it soon. I'll report back with any findings.

**Comment by Nabarun** [comment]
Thanks @lpatino10  for verifying this

**Comment by lpatino10** [comment]
I think I've found the issue @Nabarun and I'm working on a patch for it now. I'll update again when it's released and ready to use.

**Comment by lpatino10** [comment]
The fix is in review now. I detailed the problems in the PR if you're curious @Nabarun.

Once it's merged you should be able to upload files fine, although uploading a PDF won't quite work the way you've detailed in this issue. For a PDF, you're going to need to create a file in your Salesforce UI and query for it in your Apex code to then send it to the Discovery service. Here's an example I used while testing for this patch:

```apex
// finding PDF file uploaded to Salesforce with the name "sample_pdf"
String fileTitle = 'sample_pdf';
SObject[] queryResult = Database.query('Select VersionNumber, VersionData, Title, Origin, FileType, FileExtension, Description, ContentUrl, ContentSize, ContentLocation, ContentDocumentId From ContentVersion WHERE Title = :fileTitle');

// the VersionData property has the Blob we want to use for our file
Blob fileBlob = (Blob) queryResult[0].get('VersionData');
IBMWatsonFile.FileBuilder fileBuilder = new IBMWatsonFile.FileBuilder();
fileBuilder.body(fileBlob);
IBMWatsonFile file = fileBuilder.build();

// we need to specify the filename and content type - validators have been added to check for this
IBMDiscoveryV1Models.AddDocumentOptions options = new IBMDiscoveryV1Models.AddDocumentOptionsBuilder()
  .environmentId('<environment_id>')
  .collectionId('<collection_id>')
  .file(file)
  .filename('sample_pdf')
  .fileContentType(IBMWatsonHttpMediaType.APPLICATION_PDF)
  .build();

IBMDiscoveryV1Models.DocumentAccepted resp = discovery.addDocument(options);
```

However, for something simpler, you can just use a JSON string in pretty much the same way you were doing:

```apex
IBMWatsonFile file = new IBMWatsonFile.FileBuilder()
  .body(Blob.valueOf('{ "key": "value" }'))
  .build();

IBMDiscoveryV1Models.AddDocumentOptions options = new IBMDiscoveryV1Models.AddDocumentOptionsBuilder()
  .environmentId('<environment_id>')
  .collectionId('<collection_id>')
  .file(file)
  .filename('sample_json')
  .fileContentType(IBMWatsonHttpMediaType.APPLICATION_JSON)
  .build();

IBMDiscoveryV1Models.DocumentAccepted resp = discovery.addDocument(options);
```

Hopefully the patch clears everything up for you. Feel free to open this issue back up or create a new one if there are still problems.

**Comment by Nabarun** [comment]
Thanks @lpatino10 let me try the solution and respond back to you.

**Comment by Nabarun** [comment]
I merged the changes and confirm I am no longer getting the timeout issue. But still the file is not getting inserted in my collection. I will debug more and update with the response.

**Comment by Nabarun** [comment]
I am able to get the file upload working for me. Thanks for all your support.

**Comment by germanattanasio** [comment]
Thanks @Nabarun for your patience and @lpatino10 for your help to get this resolve

![impressive](https://user-images.githubusercontent.com/313157/39579130-02708f5c-4eb4-11e8-95cc-e4f4030490ca.jpg)
