### ISSUE TITLE
[Discovery]: Add @isTest to IBMWatsonMockResponses

### ISSUE THREAD

**Issue by maniax89** [watson-developer-cloud/salesforce-sdk#116]
### When reporting a bug, please be sure to include the following

- [X] Salesforce version: all
- [X] SDK version: 2.0
- [X] Steps to reproduce: 
         - `sfdx force:apex:test:run`
- [X] Expected behavior: 
         - all test-related classes are excluded from code coverage
- [X] Actual behavior: 
         - `IBMWatsonMockResponses` class is included in code coverage (and lowers coverage significantly)

### When you open an issue for a feature request, please add as much detail as possible

- [X] A descriptive title starting with the service name: Conversation, Discovery...
- [X] A description of the problem you're trying to solve:
         - trying to include SDK v2.0.0 with just Discovery + Core and test coverage is too low for a managed package
- [X] A suggested solution if possible
         - add `@isTest` to the `IBMWatsonMockResponses` class to remove it
         - turn all the `IBMWatsonMockResponses` into static resources and load the JSON instead of embedding JSON into code

**Comment by lpatino10** [comment]
I'll be doing a release today or tomorrow, so I'll package this fix in.
