### ISSUE TITLE
Request time out while inserting file

### ISSUE THREAD

**Issue by Nabarun** [watson-developer-cloud/salesforce-sdk#130]
Opening issue as I see the 500 request timeout error again. Here is the sample code where I am doing file insert but am getting this response. Let me know if I am doing anything wrong

Line: 152, Column: 1IBMWatsonServiceExceptions.InternalServerErrorException: { "code" : 500, "error" : "Request timed out, please try again." }

```java
// finding PDF file uploaded to Salesforce with the name "sample_pdf"
String fileTitle = 'SalesSummit-ebrochure';
SObject[] queryResult = Database.query('Select VersionNumber, VersionData, Title, Origin, FileType, FileExtension, Description, ContentUrl, ContentSize, ContentLocation, ContentDocumentId From ContentVersion WHERE Title = :fileTitle');

IBMDiscoveryV1 discovery = new IBMDiscoveryV1('2017-11-07');

// the VersionData property has the Blob we want to use for our file
Blob fileBlob = (Blob) queryResult[0].get('VersionData');
IBMWatsonFile.FileBuilder fileBuilder = new IBMWatsonFile.FileBuilder();
fileBuilder.body(fileBlob);
IBMWatsonFile file = fileBuilder.build();

// we need to specify the filename and content type - validators have been added to check for this
IBMDiscoveryV1Models.AddDocumentOptions options = new IBMDiscoveryV1Models.AddDocumentOptionsBuilder()
  .environmentId('<<environment id>>')
  .collectionId('<<collectionid>>')
  .file(file)
  .filename('SalesSummit-ebrochure')
  .fileContentType(IBMWatsonHttpMediaType.APPLICATION_PDF)
  .build();

IBMDiscoveryV1Models.DocumentAccepted resp = discovery.addDocument(options);
```

**Comment by lpatino10** [comment]
Are you using the same SDK version you did in the last issue you created or the newest one?

**Comment by Nabarun** [comment]
@lpatino10  I am using '2018-02-16' version. It was working for me last time you made changes, yesterday when I retried it started breaking with the same 500 timeout issue

**Comment by Nabarun** [comment]
It has been opened for 24 days, can we get some traction here. This is delaying the schedule for our component from getting published to market place

**Comment by lpatino10** [comment]
Sorry for the delay @Nabarun. I'll take a look as soon as I get the chance.

**Comment by Nabarun** [comment]
Thanks @lpatino10

**Comment by lpatino10** [comment]
Closing as this issue should be fixed in the [newest release](https://github.com/watson-developer-cloud/salesforce-sdk/releases/tag/v2.3.2).
