### ISSUE TITLE
Missing confidence score - Watson Discovery Services 

### ISSUE THREAD

**Issue by wilsonwong13** [watson-developer-cloud/salesforce-sdk#137]
Currently, when you make a request to a Watson Discovery instance that is already been trained, you don't get the confidence score. 

https://console.bluemix.net/docs/services/discovery/train-tooling.html#improving-result-relevance-with-the-tooling

**Comment by lpatino10** [comment]
Closing as this has been added to the `QueryResultResultMetadata` model as part of the [latest release](https://github.com/watson-developer-cloud/salesforce-sdk/releases/tag/v2.4.0)
