### ISSUE TITLE
[Discovery] Allow JSON to pass-through to calling method

### ISSUE THREAD

**Issue by maniax89** [watson-developer-cloud/salesforce-sdk#160]
Right now the SDK can produce significantly large heap sizes while serializing/deserializing JSON responses. Many times with large documents we are getting https://salesforce.stackexchange.com/questions/143598/exceeded-max-size-limit-of-6000000

I think to buy us some time, we could potentially pass the JSON response (in this case Discovery) directly to the calling method with a parameter of some sort like `raw = true` or a different method like `queryRaw` that just returns the response body as-is instead of attempting to deserialize it.

### When reporting a bug, please be sure to include the following

- [X] Salesforce version: Fall 2018
- [X] SDK version: 2.9.0
- [X] Steps to reproduce: using Watson Discovery, make a query that produces a fairly large response/result set - when the response exceeds 6MB, it fails
- [X] Expected behavior: the apex code errors out with large JSON responses
- [X] Actual behavior: the apex code doesn't error out with large JSON responses

### When you open an issue for a feature request, please add as much detail as possible

- [X] A descriptive title starting with the service name: Conversation, Discovery...
- [X] A description of the problem you're trying to solve: see above
- [X] A suggested solution if possible: see above

**Comment by germanattanasio** [comment]
We are not going to support this. Happy to review. PR
