### ISSUE TITLE
Deployment Errors

### ISSUE THREAD

**Issue by Lucas-Kanter** [watson-developer-cloud/salesforce-sdk#182]
When cloning and attempting to deploy the SDK version from 05/08/19 to a new Salesforce developer edition, I encountered errors saying that the IBMWatsonService is invalid and needs to be recompiled. I followed the instructions in the readme. I cloned the repo, navigated to the directory, authenticated my org, and tried to deploy the mdapioutput folder. The terminal errors are attached. 
<img width="1271" alt="Screen Shot 2019-05-08 at 1 13 50 PM" src="https://user-images.githubusercontent.com/40608833/57399195-cc6d5700-719e-11e9-9975-60dab5fb4ef5.png">

**Comment by lpatino10** [comment]
Hey @Lucas-Kanter, thanks for pointing this issue out. It looks like it was a silly mistake that somehow wasn't caught with the CI config. I'll put in a patch ASAP.

**Comment by lpatino10** [comment]
This issue should be resolved in the latest release (v4.0.2).
