### ISSUE TITLE
Ignore deployment of functional test classes to Salesforce orgs

### ISSUE THREAD

**Issue by lpatino10** [watson-developer-cloud/salesforce-sdk#26]
The functional tests are there as a reference for developers and, in the future, for use in Travis to ensure code quality. They should be kept out of deployment to Salesforce to try and keep the total package size down. This should ideally be implemented for all three deployment methods.

**Comment by magdielhf** [comment]
Tried using the ant deployment script and creating scratch orgs using the current git structure, the functional tests are not deployed
