### ISSUE TITLE
Release Text to Speech and Speech to Text

### ISSUE THREAD

**Issue by lpatino10** [watson-developer-cloud/salesforce-sdk#40]
**Acceptance Criteria:**
- [x] Merge `text-to-speech` and `speech-to-text` branches into `develop`
- [x] Merge `develop` into `master`
- [x] Update any necessary documentation (README, release notes, etc.)

**Comment by germanattanasio** [comment]
Since Apex doesn't support WebSocket we will update the README with the instructions on how to use the speech-javascript-sdk
