### ISSUE TITLE
Regenerate all current services

### ISSUE THREAD

**Issue by lpatino10** [watson-developer-cloud/salesforce-sdk#42]
Since services have released, changes have been made to the APIs. We should regenerate all services to capture any changed/new functionality.

**Acceptance Criteria:**
- [x] Regenerate all services and put in new `api-update` branch
- [x] Update failing tests or add new ones to capture any changes in functionality
- [ ] Update change log to explain breaking changes

**Comment by germanattanasio** [comment]
@lpatino10, I think this is something you did already. If that's the case, can you also provide the manual changes to the generated code?

**Comment by lpatino10** [comment]
I started on this but never finished. I'm working on it now though while noting the manual changes at the same time.
