### ISSUE TITLE
Ensure scratch orgs created in Travis are always deleted

### ISSUE THREAD

**Issue by lpatino10** [watson-developer-cloud/salesforce-sdk#50]
In our Travis build script, we create a temporary scratch org to make sure the code compiles and passes all tests. This org is deleted after a successful build, but the deletion command gets passed over if the build fails.

This has resulted in a lot of built up scratch orgs, and there's a limit of 40 we can have at a time. We should tweak the script to always delete the temporary org, no matter the build result.

**Comment by sumeetbath** [comment]
travis build is now deleting org in all scenarios.
