### ISSUE TITLE
When using an attachment we should not ask for filename or contentType

### ISSUE THREAD

**Issue by lpatino10** [watson-developer-cloud/salesforce-sdk#51]
This 
```apex
IBMDiscoveryV1Models.AddDocumentOptionsBuilder()
      .environmentId(environmentId)
      .collectionId(collectionId)
      .file(testfile)
      .filename(att.Name)
      .fileContentType(att.ContentType)
      .build();
```
Should be
```
IBMDiscoveryV1Models.AddDocumentOptionsBuilder()
      .environmentId(environmentId)
      .collectionId(collectionId)
      .file(testfile)
      .build();
```

This means setting the filename and content type inside the setter for `file`. You should still be able to set those manually if you want, though.

**Comment by lpatino10** [comment]
Right now there's not a great way to add this feature to the generator that I know of. We can tweak the template for builders to do something like this:

```apex
public AddDocumentOptionsBuilder file(File file) {
  this.file_serialized_name = file;
  if (file.name != null) {
    this.____ = file.name;
  }
  if (file.contentType != null) {
    this.____ = file.contentType();
  }
  return this;
}
```

The only issues are those blank lines, because we don't know for sure what they variable names will be for filenames and content types, as they differ between models and services.

It's possible that there's a change that can be made in the generator logic, but that'll require further investigation.

**Comment by germanattanasio** [comment]
I'm closing this as won't fix then.
