### ISSUE TITLE
Error deploying all Services with Ant

### ISSUE THREAD

**Issue by murcix** [watson-developer-cloud/salesforce-sdk#65]
I have tried deploy all services provided in the SDK using ant to my Developer Edition Org. I have followed the steps and I got the next errors:

IBMDiscoveryV1 | Apex Class | 77 | 13 | Dependent class is invalid and needs recompilation: IBMDiscoveryV1Models: line 734, column 140: Initial term of field expression must be a concrete SObject: Map<String,Object>

IBMDiscoveryV1Models | Apex Class | 734 | 140 | Initial term of field expression must be a concrete SObject: Map<String,Object>

IBMDiscoveryV1Test | Apex Class | 13 | 36 | Dependent class is invalid and needs recompilation: Class.IBMDiscoveryV1.createEnvironment: line 77, column 13 IBMDiscoveryV1Models: line 734, column 140: Initial term of field expression must be a concrete SObject: Map<String,Object>

IBMWatsonServiceTest | Apex Class | 25 | 38 | Dependent class is invalid and needs recompilation: Class.IBMDiscoveryV1.createEnvironment: line 77, column 13 IBMDiscoveryV1Models: line 734, column 140: Initial term of field expression must be a concrete SObject: Map<String,Object>

**Comment by wilsonwong13** [comment]
Having the same issue

**Comment by lpatino10** [comment]
Hey @murcix and @wilsonwong13, thanks for bringing this issue up. I think this is a weird issue that someone else on the dev team had but that I've never been able to duplicate..

If one or both of you could make the following small changes to your `IBMDiscoveryV1Models` file and let me know if that clears it up for you, I'll add the fix to the next release. The changes are as follows:

On line 722, change the name of the variable from `trainingStatus` to `trainingStatusMap`. The line should now look like this:

```
Map<String, Object> trainingStatusMap = (Map<String, Object>) jsonMap.remove('training_status_serialized_name');
```

Then on line 734, change the references to the old `trainingStatus` variable. The line should now look like this:

```
TrainingStatus newTrainingStatus = (TrainingStatus) new TrainingStatus().deserialize(JSON.serialize(trainingStatusMap), trainingStatusMap, TrainingStatus.class);
```

**Comment by murcix** [comment]
Hello @lpatino10 

Thank you very much. With the change  suggested works fine!

Regards
