### ISSUE TITLE
[Discovery] Annotate tests with @isTest

### ISSUE THREAD

**Issue by maniax89** [watson-developer-cloud/salesforce-sdk#7]
#### Problem

The SDK package is 1.3MB when deployed. This is too large for applications that want to include it within their package (since this is an unmanaged package).

#### Solution

The tests in the package should be annotated with `@isTest` so they are not deployed with a parent application package. 

This will cut down the size of the files pushed when using the SDK that will help other applications stay under the 3MB limit of packages on Salesforce AppExchange

### When reporting a bug, please be sure to include the following

- [X] Salesforce version: N/A
- [X] SDK version: 0.1.1
- [X] Steps to reproduce: try deploying the SDK using `sfdx` and see that all tests are pulled in that are not annotated
- [X] Expected behavior: tests are excluded
- [X] Actual behavior: tests are included

### When you open an issue for a feature request, please add as much detail as possible

- [X] A descriptive title starting with the service name: Conversation, Discovery...
- [X] A description of the problem you're trying to solve
- [X] A suggested solution if possible

**Comment by germanattanasio** [comment]
Fixed in #6
