### ISSUE TITLE
Investigate deserialization failure

### ISSUE THREAD

**Issue by lpatino10** [watson-developer-cloud/salesforce-sdk#70]
The Conversation service shown [here](https://github.com/germanattanasio/salesforce-sdk/wiki/Embeding-Watson-Conversation-Service-into-your-Salesforce-applications-has-never-been-this-easy) was working before, but a recent test of it is returning errors when the `Context` object is not `null`.

This should be investigated in case it has any further implications about a deserialization bug with dynamic objects.

**Comment by germanattanasio** [comment]
Is this still an issue?

**Comment by lpatino10** [comment]
As far as I know, yes. I haven't looked at it since writing the issue but plan to investigate next week.
