### ISSUE TITLE
Personality Insights, content_items_serialized_name param is invalid

### ISSUE THREAD

**Issue by Pheosh** [watson-developer-cloud/salesforce-sdk#77]
"contentItems" JSON parameter for Personality Insights watson request is case sensitive and doesn't contain an underscore. This parameter (named "content_items_serialized_name") is incorrect in IBMPersonalityInsightsV3Models class which is causing following error: "{"code":400,"sub_code":"S00005","error":"Invalid JSON input at line 1, column 19"}".

Solution:
"content_items_serialized_name" attribute (all references) in IBMPersonalityInsightsV3Models class should be changed to "contentItems_serialized_name".

**Comment by germanattanasio** [comment]
Thanks a lot for filing this issue! Would you like to write a patch for this? We'd be more than happy to walk you through the steps involved. Check the CONTRIBUTING.md for an example.

**Comment by lpatino10** [comment]
Hey @Pheosh, thanks for the heads up. I've gone ahead and made the change, so it should be up in the `master` branch shortly.

**Comment by germanattanasio** [comment]
Fixed in #81
