### ISSUE TITLE
[Discovery] Query Results not available in Javascript (AuraEnabled)

### ISSUE THREAD

**Issue by maniax89** [watson-developer-cloud/salesforce-sdk#9]
### Problem

When I write the code like the following:

```
String environmentId = 'myEnvironmentId';
List<String> collectionIDs = new List<String>();
collectionIDs.add('collectionId1');
collectionIDs.add('collectionId2');
String query = 'my query';

IBMDiscoveryV1 discovery = new IBMDiscoveryV1(IBMDiscoveryV1.VERSION_DATE_2017_09_01);
IBMDiscoveryV1Models.FederatedQueryOptions options = new IBMDiscoveryV1Models.FederatedQueryOptionsBuilder(environmentId, collectionIDs).naturalLanguageQuery(query).build();

System.debug(discovery.federatedQuery(options).getResults());
```

I get the following response:
```
[
  {
    "id": "my_id",
    "score": 1.0,
    "collection_id": "my_collection_id",
    "additional_properties" : {
       //more fields here
    }
  }
]
```

However, when I try to access the same response in Javascript (aura) layer with the following code:

```
action.setParams({
    "environmentId": "myEnvironmentId",
    "collectionIDs": ["collectionId1", "collectionId2"],
    "query": "my query"
});
action.setCallback(this, function(response) {
    var resp = response.getReturnValue();
    console.log(resp.results);
});
$A.enqueueAction(action);
```

I get the following:

```
[
  {
    "id": "my_id",
    "score": 1.0,
    "collection_id": "my_collection_id"
  }
]
```

#### Expected

I expect to be able to retrieve the following response for both situations:
```
[
  {
    "id": "my_id",
    "score": 1.0,
    "collection_id": "my_collection_id",
    //more fields here
  }
]
```

(specifically, no `additional_properties` object)

#### Solution

I believe an `@AuraEnabled` flag needs placed somewhere on the dynamic models for the parent class of `IBMDiscoveryV1Models.QueryResult`. Not exactly clear where.

**Comment by magdielhf** [comment]
Some of the restrictions for adding an `@AuraEnabled` flag that currently pose a challenge for the dynamic part of the models include:

- Parameters cannot be passed into non-static methods
- the keyword `get` needs to be present for instance methods, from here the method `deserialize` would become `getDeserialize` therefore not having a virtual declaration on the base class `IBMWatsonDynamicModel`

In the meantime the dynamic part of the models are adjusted to be visible from Lightning, a workaround could be returning just a String from the action using this code 

`return JSON.serialize(discovery.federatedQuery(options).getResults());`

From the client or the lightning component, then do the reverse operation, 

`var QueryResultList = JSON.parse(response.getReturnValue());`

**Comment by benjdewan** [comment]
A negative side effect of the serialize/parse approach is that every single resulting field gets `_serialized_name` appended to it because Apex uses the class variable names as keys.

**Comment by maniax89** [comment]
FYI, to go along with what @benjdewan was saying, the approach suggested actually outputs a rather unusable JSON string.

Example, given a query result from WDS like this:
```
{
  "id": "d3bc1fbb27320771e436af4c48b8e9e49835930f47a1fac65cbfc4280d0ce268",
  "score": 0.13112299,
  "collection_id": "7f6b6c22-db23-4626-93d5-81b53b98f9fd",
  "metadata": null,
  "CASENUMBER": "00001001",
  "STATUS": "Closed",
  "ISCLOSED": "true",
  "ROWID": "500f0000007AmhlAAC",
  "extracted_metadata": {
    "sha1": "6b095bc7b521452cd5f9e60ae841ab2956969095",
    "filename": "filename",
    "file_type": "json"
  },
  "SUBJECT": "Performance inadequate for second consecutive week",
  "REASON": "Performance",
  "OBJECT_TYPE": "CASE",
  "CLOSEDDATE": "2016-09-19 14:59:51.0"
}
```

the workaround approach produces this:
```
{
  "additional_properties": {
    "CASENUMBER_serialized_name": "00001001",
    "STATUS_serialized_name": "Closed",
    "ISCLOSED_serialized_name": "true",
    "ROWID_serialized_name": "500f0000007AmhlAAC",
    "extracted_metadata_serialized_name": {
      "sha1_serialized_name": "6b095bc7b521452cd5f9e60ae841ab2956969095",
      "filename_serialized_name": "filename",
      "file_type_serialized_name": "json"
    },
    "SUBJECT_serialized_name": "Performance inadequate for second consecutive week",
    "REASON_serialized_name": "Performance",
    "OBJECT_TYPE_serialized_name": "CASE",
    "CLOSEDDATE_serialized_name": "2016-09-19 14:59:51.0"
  },
  "score_serialized_name": 0.13112299,
  "metadata_serialized_name": null,
  "id_serialized_name": "d3bc1fbb27320771e436af4c48b8e9e49835930f47a1fac65cbfc4280d0ce268",
  "collection_id_serialized_name": "7f6b6c22-db23-4626-93d5-81b53b98f9fd"
}
```
